### ISSUE TITLE
Jinja2 and Vue.js delimiter

### ISSUE THREAD

**Issue by anselal** [frostming/flask-vue-todo#1]
Hi there,

Very educational example app.
I am writing my own app trying to migrate my UI from Jinja2 to Vue.js and I have a question:

How does the `{{ csrf_token() }}` in `index.html` get rendered via Jinja2 and the rest of the of the double curly braces get rendered via vuejs?

In my example the token does not get rendered

**Comment by frostming** [comment]
You mean https://github.com/frostming/flask-vue-todo/blob/master/frontend/index.html?

There only exist one pair of double curly braces, which are rendered as Jinja2 template delimiter. Vue.js templates are built into a single js file and injected to `index.html` later.

**Comment by anselal** [comment]
Oh, you are right about that, didn't think of it that way.
The strange thing is that when I open the source code of my endpoint were index.html is rendered, the csrf token is not processed by jinja and I cannot post or get.
Can you maybe think of something I am doing wrong?

**Comment by anselal** [comment]
I managed to fix that, I had something cached in the browser probably. Now When I submit the form I get the error `The CSRF token is missing` although it gets rendered.

**Comment by anselal** [comment]
Fixed that, I used `axios.get` by mistake instead of `axios.post`
