### ISSUE TITLE
Move `isLoggedIn` to the store

### ISSUE THREAD

**Issue by anselal** [frostming/flask-vue-todo#2]
Hi there again,

I am trying to move `isLoggedIn` to the store so I can use state, mutations and getters for the login.

In store/state.js:
```sh
import api from '../api'

export default {
  isLoggedIn: api.getSession() ? true : false
}
```

In store/mutations.js
```sh
export default {
  login(state) {
    state.authorized = true
  },
  logout(state) {
    state.authorized = false
  },
}
```

In store/getters.js
```sh
export default {
  authorized: state => state.authorized,
};
```

And on login I call `this.$store.commit('login')`, on logout `this.$store.commit('logout')`

The thing is that `this.$store.getters.authorized` returns always true if I refresh

Any idea how to fix it ?

**Comment by frostming** [comment]
It seems `isLoggedIn` in the state should be `authorized`?
Also `api.getSession()` is an async function that returns a `Promise`, while you are testing against it which will always be `true`. The following is how to do it rightly, I put all components in one file while you can split them into their own files
store/auth.js:
```javascript
import api from '../api'

const state = {
  authorized: false
}
const mutations = {
  setAuthorized(state, authorized) {
    state.authorized = authorized
  }
}
const actions = {
  login({ commit }, formData) {
    api.login(formData).then(resp => {
      commit('setAuthorized', true)
    })
  },
  logout({ commit }) {
    api.logout().then(resp => {
      commit('setAuthorized', false)
    }
  },
  checkLogin({ commit }) {
    api.getSession().then(resp => {
      commit('setAuthorized', true)
    }
  }
}

export default {
  state,
  mutations,
  actions
}
```
Then you need to check the login state in `mounted()` of the out most Vue component:
```javascript
mounted() {
  this.$store.dispatch('checkLogin')
}
```

**Comment by frostming** [comment]
No more update, close it now.

**Comment by anselal** [comment]
Yeah, sorry.. Forgot about that.
This is a real good solution IMO, you should update your code according to that.

**Comment by anselal** [comment]
Hi there,

so, how do I get `authorized` from the state ?

I found out I can use the following:

```sh
<template>
  <div class="home">>
    <p v-if="authorized">User logged in</p>
    <p v-else>user not logged in</p>
    <p>{{ authorized }}</p>
  </div>
</template>


import { mapState } from "vuex";

export default {
  computed: {
    ...mapState(["authorized"])
  },
  mounted() {
    this.$store.dispatch("checkLogin");
  }
};
```

but the template always returns that the user is not logged in, although I can get a session from the endpoint.

Am I missing something ???

**Comment by anselal** [comment]
Hi @frostming,

how do replace the `api.login` call in the Login component with a store dispatch based on the above auth.js module ?
