### ISSUE TITLE
auth/session returns 401 when user not connected

### ISSUE THREAD

**Issue by anselal** [frostming/flask-vue-todo#3]
Hi there,

the following lines return an error when there is no active user session

https://github.com/frostming/flask-vue-todo/blob/e5330497bb0a5457778160aeff0082549214d06a/frontend/src/components/Home.vue#L16-L18

The error is the following:

```sh
Uncaught (in promise) Error: Request failed with status code 401
```

Wouldn't it be better if we return code 200, and check for the returned status to avoid getting errors in the console ???

**Comment by frostming** [comment]
I personally don't think so. The error is output to the console because the error is not handled. You can add a `catch` after the line like:
```javascript
api.getSession().then(resp => {
  vm.isLoggedIn = true
}).catch(e => {
  vm.isLoggedIn = false
}
```
It looks better than an if-clause to me.

**Comment by anselal** [comment]
Still getting the error printed to the console after adding a `catch`

**Comment by anselal** [comment]
Still getting the error printed to the console after adding a catch

**Comment by frostming** [comment]
@anselal you may need to force refresh the page since the static files are cached.

**Comment by anselal** [comment]
I think I tried that but let me check again..

**Comment by anselal** [comment]
Still the same. I guess this is default behaviour of the console?

Even on the login when I catch the errors and show them via an alert like:

```js
api.login({
          username: this.username,
          password: this.password,
          remember: this.remember
        })
        .then(() => {
          this.$store.commit("login");
          this.$router.push("/dashboard");
        })
        .catch(e => {
          let errors = e.response.data.message;
          for (let key in errors) {
            errors[key].forEach(e => {
              alert(`${key}: ${e}`);
            });
          }
        });
```

I still get the errors in the console. Catching them probably prevent the app to crash or it's just a way to do something when the error occurs ?

Did you try it your self? Does your solution work for you ?

**Comment by frostming** [comment]
![image](https://user-images.githubusercontent.com/16336606/75960882-e0d3ca80-5efb-11ea-9d08-c7fbcef0f3cf.png)
No more `Uncaught error`, it is NOT the same

**Comment by anselal** [comment]
Yes, indeed it is not the same.
The only way I found to get rid of that error is what I mentioned earlier, thus not returning 401 but an error in the json and then checking for that error. Is there perhaps another solution ?

Thnx for the feedback

**Comment by frostming** [comment]
No, but I think it is totally tolerable to me, you can't assume that only 2xx should be returned

**Comment by anselal** [comment]
You are absolutely right on that !!
 thnx again !!!
